---
title: "datawrangle_NYPDbikes"
author: "Sam Chew Chin"
date: "2025-10-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
library(tools)




```
# Read in data
```{r}
#raw
rawdat<-read_csv("data/crashdata.csv")
  
spec(rawdat)

```


```{r rename}

#rename and reformat key variables

crashdat<-rawdat%>%
  mutate(date=mdy(`CRASH DATE`))%>%
  relocate(date)%>%
  rename(time=`CRASH TIME`, 
         lat=LATITUDE,
         lon=LONGITUDE,
         street=`ON STREET NAME`,
         cross=`CROSS STREET NAME`,
         cycle_inj=`NUMBER OF CYCLIST INJURED`,
         cycle_kill=`NUMBER OF CYCLIST KILLED`)


#filter out missing coords, date
crashfilt<-crashdat%>%
    filter(!is.na(lat), 
           !is.na(lon), 
           !is.na(date),
           lon!=0,
           lat!=0)

write_csv(crashfilt, "data/crashfilt.csv")

#rejected data
crashrej<-crashdat%>%
    filter(is.na(lat)| 
           is.na(lon)| 
           is.na(date)|
           lon==0|
           lat==0)

write_csv(crashrej, "data/crashrej.csv")


```

```{r rej review}
rejected<-crashrej%>%
  select(date, time, lat, lon, injured=cycle_inj, killed=cycle_kill, street, cross)



```



```{r reject summary}
rejsumm<-crashrej%>%
    select(date, time, lat, lon, injured=cycle_inj, killed=cycle_kill, street, cross)%>%
  summarize(injured=sum(injured), killed=sum(killed))


monthly_rejects<-rejsumm%>%
    select(date, time, lat, lon, injured=cycle_inj, killed=cycle_kill, street, cross)%>%
    mutate(
    date  = as.Date(date),
    month = as.numeric(format(date, "%m")), 
    year = as.numeric(format(date,"%y"))
    )%>%
  group_by(year, month)%>%
  summarize(injured=sum(injured), killed=sum(killed))%>%
  ungroup()%>%
  mutate(monthyear=paste0(year,"-",month))%>%
  select(monthyear, injured, killed)%>%
  pivot_longer(cols = c(injured, killed), names_to = "type")


```





# app filter
```{r app filter}
#strip down to minimal for shiny app
appdat<-crashfilt%>%
  select(date, time, lat, lon, injured=cycle_inj, killed=cycle_kill, street, cross)%>%
 mutate(
    date  = as.Date(date),
    month = as.numeric(format(date, "%m")),
    fancydate = as.character(format(date, "%b %d, %Y")
      )) %>%
  mutate(
    # Clean and title-case street names
    street = street %>%
      str_trim() %>%
      # na_if("") %>%
      str_to_title(),
    
    cross = cross %>%
      str_trim() %>%
      # na_if("") %>%
      str_to_title()
  ) %>%
  mutate(
    popup_label = sprintf(
      "<b>Date:</b> %s<br><b>Injured:</b> %d<br><b>Killed:</b> %d%s%s",
      fancydate,
      injured,
      killed,
      ifelse(street != ""&!is.na(street), paste0("<br><b>Street:</b> ", street), ""),
      ifelse(cross != ""&!is.na(cross), paste0("<br><b>Cross:</b> ", cross), "")
    )
  )

# Save final dataset
appdata <- appdat %>%
  select(date, month, lon, lat, injured, killed, popup_label)

write.csv(appdata, "NYPD_Bike_DataDashboard/appdata.csv", row.names = FALSE)
```


```{r dummy data}

dff<-data.frame(
    lon = runif(200, -73.99, -73.90),
    lat = runif(200, 40.70, 40.80),
    injured = sample(0:3, 200, replace = TRUE),
    killed = sample(0:1, 200, replace = TRUE),
    date = Sys.Date() - sample(1:365, 200, replace = TRUE),
    time = sprintf("%02d:%02d", sample(0:23,200,replace=TRUE), sample(0:59,200,replace=TRUE)))


```


```{r check data}
#avg injuries per month
appdat%>%
  mutate(month=month(date), year=year(date))%>%
  group_by(month, year)%>%
  summarise(sum_inj =sum(injured))%>%
  ungroup()%>%
  group_by(month)%>%
  summarise(mean_inj=mean(sum_inj))


```

```{r check data}
#avg kill per month
appdat%>%
  mutate(month=month(date), year=year(date))%>%
  group_by(month, year)%>%
  summarise(sum_kill =sum(killed))%>%
  ungroup()%>%
  group_by(month)%>%
  summarise(mean_kill=mean(sum_kill))


```




# Viridis pallete viewer


```{r pallete checker}
library(viridis)


# Palette codes and names
pal_codes <- c("A","B","C","D","E","F")
pal_names <- c("Viridis","Magma","Plasma","Inferno","Cividis","Rocket")

# Number of colors per palette
n_colors <- 7

# Build a data frame with palette code, name, color, and position
pal_list <- lapply(seq_along(pal_codes), function(i) {
  data.frame(
    Code = pal_codes[i],
    Name = pal_names[i],
    Color = viridis(n_colors, option = pal_codes[i]),
    Position = seq_len(n_colors),
    stringsAsFactors = FALSE
  )
})

pal_df <- do.call(rbind, pal_list)

# Plot swatches
ggplot(pal_df, aes(x = Position, y = 1, fill = Color)) +
  geom_tile() +
  facet_wrap(~paste(Code, Name), ncol = 1, strip.position = "left") +
  scale_fill_identity() +
  theme_void() +
  theme(strip.text = element_text(face = "bold", size = 12))




```
